stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-with-registers-base'
    encoder_input_size: 224
    encoder_params: {'dinov2_path': 'facebook/dinov2-with-registers-base', 'normalize': True}
    decoder_config_path: 'configs/decoder/ViTXL'
    # pretrained_decoder_path: 'models/decoders/medrae/model_continue_0005000.pt'
    pretrained_decoder_path: models/decoders/medrae/model_finetune_9600.pt
    noise_tau: 0.
    reshape_to_2d: True
    normalization_stat_path: 'models/stats/dinov2/wReg_base/imagenet1k/stat.pt'