stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'MedSigLIP2wNorm'
    encoder_config_path: 'google/medsiglip-448'
    encoder_input_size: 448
    encoder_params: {'model_name': 'google/medsiglip-448'}
    decoder_config_path: 'configs/decoder/ViTXL'
    pretrained_decoder_path: 'models/decoders/medsiglip/base_p16_i256/ViTXL_n08/model.pt'
    noise_tau: 0.
    reshape_to_2d: True
    normalization_stat_path: 'models/stats/siglip2/base_p16_i256/ImageNet1k/stat.pt'